# Generated by Django 5.2.8 on 2025-11-25 13:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('thumb', models.ImageField(upload_to='thumb_filmes/')),
                ('descricao', models.CharField(max_length=1000)),
                ('categoria', models.CharField(choices=[('AULAS', 'Aulas'), ('ANIMACAO', 'Animação'), ('AVENTURA', 'Aventura'), ('COMEDIA', 'Comédia'), ('DOCUMENTARIO', 'Documentário'), ('DRAMA', 'Drama'), ('FICCAO', 'Ficção'), ('GUERRA', 'Guerra'), ('ROMANCE', 'Romance'), ('TERROR', 'Terror')], max_length=20)),
                ('vizualizaoes', models.IntegerField(default=0)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
