# Generated by Django 5.2.8 on 2025-12-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filme", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filme",
            name="descricao",
            field=models.TextField(max_length=1000),
        ),
    ]
