# Generated by Django 5.2.6 on 2025-11-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filme", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filme",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("AÇÂO", "Ação"),
                    ("ROMANCE", "Romance"),
                    ("TERROR", "Terror"),
                ],
                max_length=50,
            ),
        ),
    ]
